### ISSUE TITLE
Production build cannot select mention

### ISSUE THREAD

**Issue by SargisPlusPlus** [signavio/react-mentions#634]
**Steps to reproduce:**

Cannot reproduce it. Only happens in production.

**Expected behaviour:**

**Observed behaviour:**
I can see a list of mentions when I start typing "@" but choosing the mention, it does not choose it.
When running in dev mode, it works as expected, no issues. 
In console log, I see:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'markup')
    at tt (react-mentions.esm.js:98:1)
    at tu (react-mentions.esm.js:267:1)
    at v.addMention (react-mentions.esm.js:1822:1)
    at v.selectFocused (react-mentions.esm.js:1525:1)
    at react-mentions.esm.js:1480:1
    at Object.eA (react-dom.production.min.js:55:313)
    at eq (react-dom.production.min.js:55:465)
    at react-dom.production.min.js:56:34
    at rg (react-dom.production.min.js:56:135)
```

Tech Stack:
1. react-mentions": "^4.4.7"
2. "react": "^18.2.0",
3.  "react-dom": "^18.2.0"

My code:
```
            <MentionsInput
              style={mentionsInputStyle}
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder={'Add a comment or mention with @'}
              a11ySuggestionsListLabel={'Suggested mentions'}
            >
              <Mention
                data={(teamMembers || []).map(member => {
                  const item = { id: member.id, display: `${member.first_name} ${member.last_name}` };
                  console.log("Mentions - item", item);
                  return item;
                })}
                trigger="@"
                style={mentionStyle}
              />
            </MentionsInput>
```

**Workaround:**
N/A

**Comment by claritycodeweb** [comment]
+1

**Comment by claritycodeweb** [comment]
hi, any temporary workaround for this ?

**Comment by TranLuongNam** [comment]
I also have problem like this
"react": "18.2.0",
"next": "12.3.1",
"react-dom": "18.2.0",
"react-mentions": "^4.4.10"
The issue occur when i click the mention name, see the error like image below
<img width="516" alt="image" src="https://github.com/signavio/react-mentions/assets/65284675/32e074b5-cd42-4587-8919-baee23c38308">

**Comment by cyrilzaharchenko** [comment]
Same issue here. Any suggestions on how to solve this?

**Comment by AayushMathur7** [comment]
+1

**Comment by petrikkachur** [comment]
+1

**Comment by sosegon** [comment]
Please, see [this possible solution](https://github.com/signavio/react-mentions/issues/19#issuecomment-2050271001).
