### ISSUE TITLE
Text Paste Error before typing in textarea

### ISSUE THREAD

**Issue by SirRatul** [signavio/react-mentions#718]
Getting an error when trying to paste in the react mention text area before typing anything
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at iterateMentionsMarkup (react-mentions.esm.js:111:1)
    at mapPlainTextIndex (react-mentions.esm.js:166:1)
    at MentionsInput.handlePaste (react-mentions.esm.js:1958:1)
![image](https://github.com/signavio/react-mentions/assets/46588487/1c6be302-3c29-429b-b75f-561dfd594ea5)

**Comment by hilmanfjrsy** [comment]
in my case this is happened because the default value is `undefined`, i have tried to change the default value to empty string. it's works

**Comment by tsirilson** [comment]
> in my case this is happened because the default value is `undefined`, i have tried to change the default value to empty string. it's works

This worked for me too!
